export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_ITEM = "GET_ITEM";

export const GET_SELECTED_ITEM = "GET_SELECTED_ITEM"

export const GET_SEARCH_ITEM = "GET_SEARCH_ITEM"